import React, { useState, useEffect, useRef } from 'react';
import Peer, { MediaConnection } from 'peerjs';
import { Camera, Mic, MicOff, Video, VideoOff, Wifi, WifiOff, ArrowLeft } from 'lucide-react';
import { pushMatchState, fetchMatchState } from '../services/firebaseService';
import { MatchState } from '../types';

interface CameraOperatorProps {
    onBack: () => void;
    initialMatchId?: string;
    initialJoinId?: string;
}

const CameraOperator: React.FC<CameraOperatorProps> = ({ onBack, initialMatchId, initialJoinId }) => {
    const [matchId, setMatchId] = useState(initialMatchId || '');
    const [cameraId, setCameraId] = useState('');
    const [joinId, setJoinId] = useState(initialJoinId || '');
    const [isStreaming, setIsStreaming] = useState(false);
    const [localStream, setLocalStream] = useState<MediaStream | null>(null);
    const [peer, setPeer] = useState<Peer | null>(null);
    const [isMuted, setIsMuted] = useState(true); // Default mute for secondary cams
    const [isVideoOff, setIsVideoOff] = useState(false);
    const [status, setStatus] = useState<string>('Ready to Connect');
    const [deviceLabel, setDeviceLabel] = useState<string>('Main Camera');

    const videoRef = useRef<HTMLVideoElement>(null);
    const localStreamRef = useRef<MediaStream | null>(null);

    // Initialize Camera
    useEffect(() => {
        const initCamera = async () => {
            try {
                const stream = await navigator.mediaDevices.getUserMedia({
                    video: {
                        facingMode: 'environment', // Prefer back camera for camera operators
                        width: { ideal: 1280 },
                        height: { ideal: 720 }
                    },
                    audio: true
                });
                localStreamRef.current = stream;
                setLocalStream(stream);
                if (videoRef.current) {
                    videoRef.current.srcObject = stream;
                    videoRef.current.muted = true; // Local preview always muted
                }
                const videoTrack = stream.getVideoTracks()[0];
                setDeviceLabel(videoTrack.label || 'Camera Device');
            } catch (err) {
                console.error("Camera Init Error:", err);
                setStatus("Error: Could not access camera");
            }
        };
        initCamera();

        return () => {
            stopAllTracks();
            if (peer) {
                peer.destroy();
            }
        };
    }, []);

    const stopAllTracks = () => {
        if (localStreamRef.current) {
            console.log("Stopping all media tracks...");
            localStreamRef.current.getTracks().forEach(track => {
                track.stop();
                console.log(`Stopped track: ${track.label}`);
            });
            localStreamRef.current = null;
        }
        setLocalStream(null);
    };

    // Toggle Tracks
    useEffect(() => {
        if (localStream) {
            localStream.getAudioTracks().forEach(t => t.enabled = !isMuted);
            localStream.getVideoTracks().forEach(t => t.enabled = !isVideoOff);
        }
    }, [isMuted, isVideoOff, localStream]);

    const handleStartStreaming = async () => {
        if (!matchId || !cameraId) {
            alert("Please enter both Match ID and Camera Code");
            return;
        }

        setStatus("Verifying Match ID...");
        const matchState = await fetchMatchState(matchId.toUpperCase());
        if (!matchState) {
            setStatus("Error: Match ID not found");
            return;
        }

        // 1. Verify Join ID
        if (!matchState.cameraJoinId || matchState.cameraJoinId !== joinId) {
            setStatus("Error: Invalid Camera Join ID");
            alert("The Join ID you entered is invalid or has not been generated by the scorer yet.");
            return;
        }

        // 2. Check Expiration
        if (matchState.joinIdExpiresAt && Date.now() > matchState.joinIdExpiresAt) {
            setStatus("Error: Join ID Expired");
            alert("This Join ID has expired. Please ask the scorer to refresh it.");
            return;
        }

        // 3. Check if Camera Slot exists
        const currentCameras = matchState.cameras || [];
        const cameraSlot = currentCameras.find(c => c.id === cameraId.toUpperCase());
        if (!cameraSlot) {
            setStatus("Error: Camera Slot Not Found");
            alert(`The camera slot "${cameraId}" has not been created in the Broadcast Manager.`);
            return;
        }

        if (cameraSlot.isDisabled) {
            setStatus("Error: Camera Disabled");
            alert("This camera slot has been disabled by the scorer.");
            return;
        }

        // Construct full Peer ID
        const peerId = `${matchId.toUpperCase()}_${cameraId.toUpperCase()}`;

        setStatus("Initializing Peer...");
        const newPeer = new Peer(peerId, {
            host: '0.peerjs.com',
            secure: true,
            port: 443,
            debug: 3,
            config: {
                iceServers: [
                    { urls: 'stun:stun.l.google.com:19302' },
                    { urls: 'stun:stun1.l.google.com:19302' },
                    { urls: 'stun:stun2.l.google.com:19302' },
                    { urls: 'stun:stun3.l.google.com:19302' },
                    { urls: 'stun:stun4.l.google.com:19302' },
                    { urls: 'stun:stun.services.mozilla.com' }
                ]
            }
        });

        newPeer.on('open', (id) => {
            console.log("Camera Peer Open:", id);
            setStatus("Live & Streaming");
            setIsStreaming(true);

            // Update camera status in match state
            const currentCameras = matchState.cameras || [];
            const updatedCameras = currentCameras.map(c =>
                c.id === cameraId.toUpperCase() ? { ...c, status: 'LIVE' as const } : c
            );

            if (!currentCameras.some(c => c.id === cameraId.toUpperCase())) {
                updatedCameras.push({ id: cameraId.toUpperCase(), name: `Camera ${cameraId.toUpperCase()}`, status: 'LIVE' });
            }

            const newState = { ...matchState, cameras: updatedCameras };
            pushMatchState(matchId.toUpperCase(), newState);
        });

        // HANDSHAKE LAYER: Listen for DataConnections
        newPeer.on('connection', (conn) => {
            console.log("Handshake requested from viewer on secondary camera:", conn.peer);
            conn.on('open', () => {
                conn.send({ type: 'HANDSHAKE_OK', status: 'READY' });
            });
            conn.on('data', async (data: any) => {
                if (data?.type === 'CHANGE_QUALITY') {
                    const q = data.quality;
                    console.log(`Quality change requested: ${q}`);
                    const constraints = {
                        video: q === 'HIGH' ? { width: 1920, height: 1080 } :
                            q === 'LOW' ? { width: 480, height: 360 } :
                                { width: 1280, height: 720 },
                        audio: true
                    };
                    try {
                        const newStream = await navigator.mediaDevices.getUserMedia(constraints);
                        if (localStreamRef.current) {
                            const oldTrack = localStreamRef.current.getVideoTracks()[0];
                            const newTrack = newStream.getVideoTracks()[0];
                            localStreamRef.current.removeTrack(oldTrack);
                            localStreamRef.current.addTrack(newTrack);
                            oldTrack.stop();
                            if (videoRef.current) videoRef.current.srcObject = localStreamRef.current;
                        }
                    } catch (e) {
                        console.error("Camera operator failed to change quality:", e);
                    }
                }
            });
        });


        newPeer.on('call', (call: MediaConnection) => {
            console.log("Viewer Connected to External Camera. Checking media...");
            const stream = localStreamRef.current;
            if (stream && stream.active) {
                const v = stream.getVideoTracks().length;
                const a = stream.getAudioTracks().length;
                console.log(`Answering camera call with ${v}v / ${a}a tracks.`);
                call.answer(stream);
            } else {
                console.warn("No active local stream to answer camera call");
                call.answer(new MediaStream());
            }
        });

        newPeer.on('disconnected', () => {
            console.warn("Camera signaling disconnected. Reconnecting...");
            newPeer.reconnect();
        });

        newPeer.on('error', (err) => {
            console.error("Peer Error:", err);
            setStatus(`Error: ${err.message}`);
            setIsStreaming(false);
        });

        setPeer(newPeer);
    };

    const handleStopStreaming = () => {
        if (peer) {
            peer.destroy();
            setPeer(null);
        }
        stopAllTracks();
        setIsStreaming(false);
        setStatus("Stopped");
    };

    return (
        <div className="fixed inset-0 bg-black flex flex-col z-[300]">
            {/* Top Bar */}
            <div className="flex items-center justify-between p-4 bg-slate-900/80 backdrop-blur z-20 w-full border-b border-slate-800">
                <div className="flex flex-col">
                    <h2 className="text-white text-sm font-black italic tracking-wider uppercase leading-none">Camera Operator</h2>
                    <div className="flex items-center gap-2 mt-1.5">
                        <span className={`text-[9px] font-black uppercase px-2 py-0.5 rounded transition-all ${isStreaming ? 'bg-red-600 text-white animate-pulse' : 'bg-slate-700 text-slate-400'}`}>
                            {status}
                        </span>
                        {isStreaming && (
                            <div className={`flex items-center gap-1 px-1.5 py-0.5 rounded border text-[8px] font-black uppercase tracking-widest ${peer?.open ? 'bg-green-500/10 text-green-500 border-green-500/20' :
                                    'bg-amber-500/10 text-amber-500 border-amber-500/20'
                                }`}>
                                {peer?.open ? 'Cloud Online' : 'Connecting...'}
                            </div>
                        )}
                    </div>
                </div>


                <button
                    onClick={() => {
                        handleStopStreaming();
                        onBack();
                    }}
                    className="px-4 py-2 bg-slate-800 hover:bg-red-600 text-white text-xs font-black rounded-full transition-colors border border-slate-700 hover:border-red-500 uppercase tracking-widest"
                >
                    Leave
                </button>
            </div>

            {/* Video Preview */}
            <div className="flex-1 relative bg-black flex items-center justify-center overflow-hidden">
                <video
                    ref={videoRef}
                    autoPlay
                    muted
                    playsInline
                    className="w-full h-full object-contain"
                />

                {/* Overlay Info */}
                <div className="absolute top-4 left-4 bg-black/50 px-2 py-1 rounded text-white text-xs font-mono">
                    {deviceLabel}
                </div>
            </div>

            {/* Controls */}
            <div className="bg-slate-900 p-6 flex flex-col gap-6 rounded-t-3xl border-t border-slate-800">
                {!isStreaming ? (
                    <div className="flex flex-col gap-4">
                        <div className="grid grid-cols-2 gap-4">
                            <div>
                                <label className="text-[10px] text-slate-500 font-black uppercase tracking-widest block mb-1">Match ID</label>
                                <input
                                    type="text"
                                    value={matchId}
                                    onChange={e => setMatchId(e.target.value.toUpperCase())}
                                    placeholder="ID"
                                    className="w-full bg-slate-800 text-white p-3 rounded-xl font-mono text-center tracking-[0.1em] font-bold border border-slate-700 focus:border-amber-500 outline-none uppercase"
                                />
                            </div>
                            <div>
                                <label className="text-[10px] text-slate-500 font-black uppercase tracking-widest block mb-1">Camera Code</label>
                                <input
                                    type="text"
                                    value={cameraId}
                                    onChange={e => setCameraId(e.target.value.toUpperCase())}
                                    placeholder="e.g. CAM1"
                                    className="w-full bg-slate-800 text-white p-3 rounded-xl font-mono text-center tracking-[0.1em] font-bold border border-slate-700 focus:border-amber-500 outline-none uppercase"
                                />
                            </div>
                        </div>
                        <div>
                            <label className="text-[10px] text-slate-500 font-black uppercase tracking-widest block mb-1">Join ID (from Scorer)</label>
                            <input
                                type="text"
                                value={joinId}
                                onChange={e => setJoinId(e.target.value)}
                                placeholder="6-digit code"
                                className="w-full bg-slate-800 text-white p-4 rounded-xl font-mono text-center tracking-[0.3em] font-black text-xl border border-slate-700 focus:border-amber-500 outline-none"
                            />
                        </div>
                        <button
                            onClick={handleStartStreaming}
                            className="w-full bg-amber-500 hover:bg-amber-400 text-black py-4 rounded-xl font-black uppercase tracking-widest shadow-lg shadow-amber-500/20 active:scale-95 transition"
                        >
                            Connect & Stream
                        </button>
                    </div>
                ) : (
                    <div className="flex flex-col gap-4">
                        <div className="grid grid-cols-2 gap-4">
                            <button
                                onClick={() => setIsMuted(!isMuted)}
                                className={`p-4 rounded-xl flex flex-col items-center justify-center gap-2 font-bold text-xs uppercase transition ${isMuted ? 'bg-slate-800 text-slate-400' : 'bg-slate-700 text-white'}`}
                            >
                                {isMuted ? <MicOff className="w-6 h-6" /> : <Mic className="w-6 h-6" />}
                                {isMuted ? 'Muted' : 'Mic On'}
                            </button>
                            <button
                                onClick={() => setIsVideoOff(!isVideoOff)}
                                className={`p-4 rounded-xl flex flex-col items-center justify-center gap-2 font-bold text-xs uppercase transition ${isVideoOff ? 'bg-slate-800 text-slate-400' : 'bg-slate-700 text-white'}`}
                            >
                                {isVideoOff ? <VideoOff className="w-6 h-6" /> : <Video className="w-6 h-6" />}
                                {isVideoOff ? 'Video Hidden' : 'Video On'}
                            </button>
                        </div>
                        <button
                            onClick={handleStopStreaming}
                            className="w-full bg-red-600 hover:bg-red-500 text-white py-4 rounded-xl font-black uppercase tracking-widest shadow-lg shadow-red-600/20 active:scale-95 transition"
                        >
                            Stop Streaming
                        </button>
                    </div>
                )}
            </div>
        </div>
    );
};

export default CameraOperator;
